apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: jenkins
        image: preedus/jenkins:v1
        volumeMounts:
        - name: jenkins-home-volume
          mountPath: /var/jenkins_home
        - name: docker-sock
          mountPath: /var/run/docker.sock
        ports:
        - containerPort: 8080
        - containerPort: 50000
      volumes:
      - name: jenkins-home-volume
        persistentVolumeClaim:
          claimName: pvc-jenkins-nfs
      - name: docker-sock
        hostPath: 
          path: /var/run/docker.sock
      #- name: jenkins-home-volume
      #  emptyDir: {}
        #hostPath: 
        #  path: /jenkins-home/
        #  type: DirectoryOrCreate


---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
