apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-nfs
  #labels:
  #  type: local
spec:
  #storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.25          # nfs server ip
    path: /shared/jenkins
      #"/srv/nfs/kubedata"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-nfs
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2500Mi