apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: willwill/wait-for-it
          command: ['sh', '-c', '/wait-for-it.sh mongo-prod.default.svc.cluster.local:27017 -t 0']
      containers:
      - name: testapp-be
        image: preedus/testapp-be:v1.1
        #imagePullPolicy: Never
        volumeMounts:
        - name: secret-volume
          mountPath: /home/node/backend/.env
          subPath: .env
        ports:
        - containerPort: 5000
      volumes:
      - name: secret-volume
        secret:
          secretName: backend-env-secret-prod
      #- name: config-volume
      #  configMap:
      #    name: backend-config
